// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

#nullable disable

namespace ParkApi.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    [Migration("20230331231033_MoreSeed")]
    partial class MoreSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "A national park in Wyoming known for its geysers, hot springs, and wildlife.",
                            Name = "Yellowstone",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "A national park in California known for its waterfalls, giant sequoia groves, and wildlife.",
                            Name = "Yosemite",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "A national park in Arizona known for its steep canyon walls, desert landscape, and wildlife.",
                            Name = "Grand Canyon",
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "A national park in Utah known for its red sandstone cliffs, canyons, and hiking trails.",
                            Name = "Zion",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "A national park in Montana known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Glacier",
                            State = "Montana"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "A national park in Washington known for its rainforests, mountains, and beaches.",
                            Name = "Olympic",
                            State = "Washington"
                        },
                        new
                        {
                            ParkId = 7,
                            Description = "A national park in Colorado known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Rocky Mountain",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 8,
                            Description = "A national park in Wyoming known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Grand Teton",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 9,
                            Description = "A national park in Maine known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Acadia",
                            State = "Maine"
                        },
                        new
                        {
                            ParkId = 10,
                            Description = "A national park in Utah known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Arches",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 11,
                            Description = "A caldera lake in Oregon known for its deep blue color and water clarity.",
                            Name = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 12,
                            Description = "A volcano in Washington known for its snow-capped peak and hiking trails.",
                            Name = "Mount Rainier",
                            State = "Washington"
                        },
                        new
                        {
                            ParkId = 13,
                            Description = "A national park in California known for its old-growth coast redwood forests.",
                            Name = "Redwood",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 14,
                            Description = "A national park in South Dakota known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Badlands",
                            State = "South Dakota"
                        },
                        new
                        {
                            ParkId = 15,
                            Description = "A national park in Texas known for its rugged mountains, alpine lakes, and abundant wildlife.",
                            Name = "Big Bend",
                            State = "Texas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
