// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

#nullable disable

namespace ParkApi.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    [Migration("20230331153923_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "PlaceHolder Text",
                            Name = "Yellowstone",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "PlaceHolder Text",
                            Name = "Yosemite",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "PlaceHolder Text",
                            Name = "Grand Canyon",
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "PlaceHolder Text",
                            Name = "Zion",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "PlaceHolder Text",
                            Name = "Glacier",
                            State = "Montana"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "PlaceHolder Text",
                            Name = "Olympic",
                            State = "Washington"
                        },
                        new
                        {
                            ParkId = 7,
                            Description = "PlaceHolder Text",
                            Name = "Rocky Mountain",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 8,
                            Description = "PlaceHolder Text",
                            Name = "Grand Teton",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 9,
                            Description = "PlaceHolder Text",
                            Name = "Acadia",
                            State = "Maine"
                        },
                        new
                        {
                            ParkId = 10,
                            Description = "PlaceHolder Text",
                            Name = "Arches",
                            State = "Utah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
